### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by GamerMJay** [Muqsit/PortableCrafting#3]
Hey, i have a idea. Can you add a Description? the description is -

**Comment by Muqsit** [comment]
A line of description in crafting tables? Or do you mean a plugin description?

**Comment by GamerMJay** [comment]
plugin description

/workbench -

**Comment by GamerMJay** [comment]
here
name: PortableCrafting
main: muqsit\portablecrafting\PortableCrafting
api: 4.0.0
version: 0.1.0
permissions:
  portablecrafting.command.workbench:
    default: true
commands:
  workbench:
    permission: portablecrafting.command.workbench
    description: Open the Workbench

**Comment by Muqsit** [comment]
Addressed in https://github.com/Muqsit/PortableCrafting/commit/b48a51b627b40a695a80dfa014f61c6f41989622 [(build #18 - PortableCrafting_dev-18.phar)](https://poggit.pmmp.io/r/164476/PortableCrafting_dev-18.phar)

**Comment by GamerMJay** [comment]
thanks

**Comment by GamerMJay** [comment]
Hello, i have a question can you add /ec?
