### ISSUE TITLE
Enderchest

### ISSUE THREAD

**Issue by PushkarOP** [Muqsit/PortableCrafting#4]
Portable enderchest

**Comment by Muqsit** [comment]
[BlockHorizons/InvSee](https://github.com/BlockHorizons/InvSee) is probably a more suitable place for this. Using that plugin, you can already grant players `invsee.enderinventory.view.self` permission to allow them to run `/enderinvsee <their name>`, but feel free to open a feature request issue there.

**Comment by Muqsit** [comment]
Added a way to configure `/echest` in InvSee: https://github.com/BlockHorizons/InvSee/blob/a7cccae0803454c0756aa122b02931cbeb504c46/resources/modules.yml#L10-L12
